spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/url-shortener
    username: my-user
    password: my-password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres
  jackson:
    time-zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes in ms
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    com.system.design: DEBUG

